const map=L.map('map',{zoomControl:false}).setView([59.3293,18.0686],15);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);
const state=JSON.parse(localStorage.getItem('omapmaker.live')||'{"observations":[],"tracks":[]}');let selected='stone',lastPosition=null,watchId=null,recording=false,currentTrack=[];const glyph={stone:'●',pit:'∨',cliff:'▰',tree:'⊙'},name={stone:'Sten',pit:'Grop',cliff:'Brant',tree:'Särskilt träd'};let gpsMarker,gpsCircle,trail;
function save(){localStorage.setItem('omapmaker.live',JSON.stringify(state))}function toast(t){const e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}function icon(type){return L.divIcon({className:'omap-symbol',html:glyph[type],iconSize:[24,24],iconAnchor:[12,12]})}function addObservation(latlng,accuracy=0){const o={id:crypto.randomUUID(),type:selected,coordinates:[latlng.lng,latlng.lat],accuracy,createdAt:new Date().toISOString(),source:'field-observation',quality:'unverified'};state.observations.push(o);L.marker(latlng,{icon:icon(selected)}).addTo(map).bindPopup(`${name[selected]}<br>GPS ±${Math.round(accuracy)} m<br>Ej verifierad`);save();toast(`${name[selected]} sparad`)}
state.observations.forEach(o=>L.marker([o.coordinates[1],o.coordinates[0]],{icon:icon(o.type)}).addTo(map));state.tracks.forEach(t=>L.polyline(t.coordinates.map(c=>[c[1],c[0]]),{className:'trail'}).addTo(map));
document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');selected=b.dataset.type;if(lastPosition)addObservation(lastPosition.latlng,lastPosition.accuracy);else toast('Starta GPS först')});
document.querySelector('[data-type="stone"]').classList.add('active');
document.querySelector('#locate').onclick=()=>{if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;document.querySelector('#locate').textContent='⌖ Starta GPS';return}watchId=navigator.geolocation.watchPosition(p=>{const latlng=L.latLng(p.coords.latitude,p.coords.longitude);lastPosition={latlng,accuracy:p.coords.accuracy};if(!gpsMarker){gpsMarker=L.circleMarker(latlng,{radius:7,color:'#fff',weight:3,fillColor:'#2677c7',fillOpacity:1}).addTo(map);gpsCircle=L.circle(latlng,{radius:p.coords.accuracy,className:'accuracy'}).addTo(map);map.setView(latlng,18)}else{gpsMarker.setLatLng(latlng);gpsCircle.setLatLng(latlng).setRadius(p.coords.accuracy)}document.querySelector('#status').classList.add('live');document.querySelector('#status span').textContent=`GPS ± ${Math.round(p.coords.accuracy)} m`;document.querySelector('#locate').textContent='■ Stoppa GPS';if(recording){currentTrack.push([p.coords.longitude,p.coords.latitude,p.coords.accuracy,Date.now()]);if(trail)trail.setLatLngs(currentTrack.map(c=>[c[1],c[0]]));else trail=L.polyline(currentTrack.map(c=>[c[1],c[0]]),{className:'trail'}).addTo(map)}},e=>toast(e.code===1?'Tillåt platsåtkomst i Safari':'GPS kunde inte hämtas'),{enableHighAccuracy:true,maximumAge:0,timeout:15000})};
document.querySelector('#track').onclick=e=>{if(!lastPosition){toast('Starta GPS först');return}recording=!recording;e.currentTarget.classList.toggle('recording',recording);e.currentTarget.textContent=recording?'■ Avsluta stig':'⌁ Spela in stig';if(recording){currentTrack=[];trail=null;toast('Stiginspelning startad')}else if(currentTrack.length>1){state.tracks.push({id:crypto.randomUUID(),type:'path',coordinates:currentTrack,createdAt:new Date().toISOString(),quality:'unverified'});save();toast('Stig sparad')}};
map.on('contextmenu',e=>addObservation(e.latlng,0));document.querySelector('#export').onclick=()=>{const features=[...state.observations.map(o=>({type:'Feature',id:o.id,properties:{type:o.type,accuracy:o.accuracy,createdAt:o.createdAt,quality:o.quality},geometry:{type:'Point',coordinates:o.coordinates}})),...state.tracks.map(t=>({type:'Feature',id:t.id,properties:{type:'path',createdAt:t.createdAt,quality:t.quality},geometry:{type:'LineString',coordinates:t.coordinates.map(c=>c.slice(0,2))}}))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({type:'FeatureCollection',features},null,2)],{type:'application/geo+json'}));a.download='omapmaker-field.geojson';a.click()};
