const workspaces=JSON.parse(localStorage.getItem('omapmaker.workspaces')||'[]');
const list=document.querySelector('#workspaceList');
let chosenCenter=null,areaMap=null,areaRectangle=null,areaBaseLayer=null;
const areaBaseMaps={osm:()=>L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap contributors'}),aerial:()=>L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Imagery © Esri'}),terrain:()=>L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenStreetMap · SRTM | OpenTopoMap'}),orientation:()=>null};
function previewBounds(center,sizeKm){const half=sizeKm/2,latDelta=half/111.32,lngDelta=half/(111.32*Math.cos(center.lat*Math.PI/180));return L.latLngBounds([center.lat-latDelta,center.lng-lngDelta],[center.lat+latDelta,center.lng+lngDelta])}
function refreshAreaPreview(){if(!areaMap)return;const center=areaMap.getCenter(),size=Number(document.querySelector('#workspaceSize').value),bounds=previewBounds(center,size);if(areaRectangle)areaRectangle.setBounds(bounds);else areaRectangle=L.rectangle(bounds,{color:'#075b3a',weight:3,fillColor:'#ddef68',fillOpacity:.18,interactive:false}).addTo(areaMap);document.querySelector('#workspaceAreaStatus').textContent=`${size} × ${size} km · ${center.lat.toFixed(5)}, ${center.lng.toFixed(5)}`}
function setAreaBasemap(id){const selected=areaBaseMaps[id]?id:'osm';if(areaBaseLayer)areaMap.removeLayer(areaBaseLayer);areaBaseLayer=areaBaseMaps[selected]();if(areaBaseLayer)areaBaseLayer.addTo(areaMap);areaMap.getContainer().classList.toggle('orientation-background',selected==='orientation');localStorage.setItem('omapmaker.areaBasemap',selected);document.querySelector('#workspaceAreaBasemap').value=selected}
function openAreaPicker(){const dialog=document.querySelector('#workspaceAreaDialog'),last=chosenCenter||JSON.parse(localStorage.getItem('omapmaker.lastCenter.global')||localStorage.getItem('omapmaker.lastCenter')||'{"lat":59.3293,"lng":18.0686}'),size=Number(document.querySelector('#workspaceSize').value);dialog.showModal();if(!areaMap){areaMap=L.map('workspaceAreaMap',{zoomControl:true}).setView([last.lat,last.lng],13);setAreaBasemap(localStorage.getItem('omapmaker.areaBasemap')||'osm');areaMap.on('move zoom',refreshAreaPreview)}setTimeout(()=>{areaMap.invalidateSize();areaMap.fitBounds(previewBounds(last,size),{padding:[35,35]});refreshAreaPreview()},80)}
function render(){document.querySelector('#workspaceCount').textContent=`${workspaces.length} sparade`;list.innerHTML='';if(!workspaces.length){list.innerHTML='<div class="empty">Inga arbetsområden ännu.<br>Den globala kartan är alltid tillgänglig.</div>';return}workspaces.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).forEach(w=>{const a=document.createElement('a');a.className='workspace';a.href=`field.html?workspace=${encodeURIComponent(w.id)}`;const mode=(w.symbolDisplayMode||'print')==='print'?'Utskriftsläge':'Digitalt läge';a.innerHTML=`<div><b>${w.name}</b><span>1:${Number(w.scale).toLocaleString('sv-SE')} · ${w.contourInterval} m · ${w.sizeKm} × ${w.sizeKm} km · ${mode}</span></div><i>→</i>`;list.append(a)})}
document.querySelector('#newWorkspace').onclick=()=>document.querySelector('#workspaceDialog').showModal();
document.querySelector('#aboutButton').onclick=document.querySelector('#aboutFooter').onclick=()=>document.querySelector('#aboutDialog').showModal();
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.querySelector(`#${b.dataset.close}`).close());
document.querySelector('#chooseWorkspaceArea').onclick=openAreaPicker;
document.querySelector('#cancelWorkspaceArea').onclick=()=>document.querySelector('#workspaceAreaDialog').close();
document.querySelector('#workspaceAreaBasemap').onchange=event=>setAreaBasemap(event.target.value);
document.querySelector('#locateWorkspaceArea').onclick=()=>{const button=document.querySelector('#locateWorkspaceArea'),status=document.querySelector('#workspaceAreaStatus');if(!navigator.geolocation){status.textContent='Positionering stöds inte av webbläsaren';return}button.disabled=true;button.textContent='Söker position…';navigator.geolocation.getCurrentPosition(position=>{const center={lat:position.coords.latitude,lng:position.coords.longitude},size=Number(document.querySelector('#workspaceSize').value);areaMap.fitBounds(previewBounds(center,size),{padding:[35,35],animate:true});button.disabled=false;button.textContent='◎ Min position';status.textContent=`GPS ± ${Math.round(position.coords.accuracy)} m`},error=>{button.disabled=false;button.textContent='◎ Min position';status.textContent=error.code===1?'Positionering saknar tillstånd':'Positionen kunde inte hämtas'},{enableHighAccuracy:true,maximumAge:5000,timeout:15000})};
document.querySelector('#workspaceSize').onchange=()=>{if(areaMap){const center=areaMap.getCenter(),size=Number(document.querySelector('#workspaceSize').value);areaMap.fitBounds(previewBounds(center,size),{padding:[35,35]});refreshAreaPreview()}if(chosenCenter){chosenCenter=null;document.querySelector('#chosenAreaSummary').textContent='Storleken ändrades · välj området på kartan igen.'}};
document.querySelector('#confirmWorkspaceArea').onclick=()=>{const center=areaMap.getCenter(),size=Number(document.querySelector('#workspaceSize').value);chosenCenter={lat:center.lat,lng:center.lng};document.querySelector('#chosenAreaSummary').textContent=`Valt område: ${size} × ${size} km runt ${center.lat.toFixed(5)}, ${center.lng.toFixed(5)}`;document.querySelector('#chooseWorkspaceArea span').textContent='Ändra plats och område';document.querySelector('#workspaceAreaDialog').close()};
document.querySelector('#workspaceForm').onsubmit=e=>{e.preventDefault();if(!chosenCenter){openAreaPicker();return}const now=new Date().toISOString();const w={id:crypto.randomUUID(),name:document.querySelector('#workspaceName').value.trim(),scale:Number(document.querySelector('#workspaceScale').value),contourInterval:Number(document.querySelector('#workspaceContour').value),symbolDisplayMode:document.querySelector('#workspaceSymbolMode').value,sizeKm:Number(document.querySelector('#workspaceSize').value),center:chosenCenter,createdAt:now,updatedAt:now,standard:'ISOM 2017-2 v6'};workspaces.push(w);localStorage.setItem('omapmaker.workspaces',JSON.stringify(workspaces));location.href=`field.html?workspace=${w.id}`};
render();
