window.OMAPMAKER_ISOM_REGISTRY = {
  "registryVersion": 13,
  "renderingRevision": 13,
  "standard": "ISOM 2017-2 Revision 6",
  "measurementBasis": {"unit":"mm","baseScale":15000,"enlargeProportionally":true},
  "colours": {
    "white":{"cmyk":[0,0,0,0],"screen":"#ffffff"},
    "black":{"cmyk":[0,0,0,100],"screen":"#111111"},
    "black20":{"cmyk":[0,0,0,20],"screen":"#cccccc"},
    "black35":{"cmyk":[0,0,0,35],"screen":"#a6a6a6"},
    "black50":{"cmyk":[0,0,0,50],"screen":"#777777"},
    "blue":{"cmyk":[100,0,0,0],"screen":"#009fc5"},
    "blue70":{"cmyk":[70,0,0,0],"screen":"#43b6d2"},
    "blue50":{"cmyk":[50,0,0,0],"screen":"#8bd3e3"},
    "yellow":{"cmyk":[0,27,79,0],"screen":"#ffd94c"},
    "yellow75":{"cmyk":[0,20,59,0],"screen":"#ffe57c"},
    "yellow50":{"cmyk":[0,14,40,0],"screen":"#ffedaa"},
    "green":{"cmyk":[76,0,91,0],"screen":"#2d9b4f"},
    "green60":{"cmyk":[46,0,55,0],"screen":"#72b96f"},
    "green30":{"cmyk":[24,0,27,0],"screen":"#b6d9a5"},
    "darkGreen":{"cmyk":[100,0,80,30],"screen":"#006b45"},
    "brown":{"cmyk":[0,56,100,18],"screen":"#a7653f"},
    "brown50":{"cmyk":[0,28,50,9],"screen":"#c9a274"},
    "yellowGreen50":{"cmyk":[38,27,100,0],"screen":"#b7c75b"},
    "purple":{"cmyk":[35,85,0,0],"screen":"#c3258d"},
    "purpleLower":{"cmyk":[35,85,0,0],"screen":"#c3258d"},
    "purpleUpper":{"cmyk":[35,85,0,0],"screen":"#c3258d"}
  },
  "colourOrder": ["white","yellow","yellow75","yellow50","green30","green60","green","yellowGreen50","blue50","blue70","brown50","black20","black35","black50","purpleLower","blue","brown","darkGreen","black","purpleUpper"],
  "overprint": {"previewBlendMode":"multiply","upperColours":["black","brown","blue"],"courseColour":"purple"},
  "textRules": {"orientation":"magnetic-north","fontFamily":"Arial, Helvetica, sans-serif","minimumSansHeightMm":1.5},
  "technical": {"601":{"lineWidthBlackMm":0.1,"lineWidthBlueMm":0.12,"spacingGroundMetres":300,"preferredColour":"black","breakForLegibility":true}},
  "preflight": {"generalGapMm":0.15,"impassableGapMm":0.4,"generalOpeningMm":0.25,"impassableOpeningMm":0.4,"generalLineLengthMm":0.6,"screenAreaMinimumWidthMm":0.4,"fullGreenMinimumWidthMm":0.25,"fullYellowMinimumWidthMm":0.3},
  "renderers": {
    "101":{"kind":"line","colour":"brown","widthMm":0.14,"minimumLengthMm":0.6,"minimumBendMm":0.25},
    "102":{"kind":"line","colour":"brown","widthMm":0.25,"minimumLengthMm":0.6,"textHeightMm":1.5},
    "103":{"kind":"dashed-line","colour":"brown","widthMm":0.1,"dashMm":[2,0.2],"minimumLengthMm":4.2,"minimumDashes":2},
    "104":{"kind":"cliff","colour":"brown","lineWidthMm":0.25,"tagWidthMm":0.14,"tagLengthMm":0.4,"tagSpacingMm":0.5,"minimumLengthMm":0.6,"requiresDirection":true,"settings":{"downhillSide":{"type":"side","required":true,"values":["left","right"],"default":"right","labelSv":"Taggarnas nedförssida"}}},
    "105.1":{"kind":"styled-line","style":"dots","colour":"brown","widthMm":0.18,"styleDiameterMm":0.45,"styleSpacingMm":2,"endGapMm":0.77,"minimumLengthMm":1.4,"minimumHeightMetres":1},
    "105.2":{"kind":"styled-line","style":"half-dots","colour":"brown","widthMm":0.18,"styleDiameterMm":0.45,"styleSpacingMm":1,"styleOffsetMm":0.58,"sideOffsetMm":0.05,"endGapMm":0.58,"minimumLengthMm":1.4,"minimumHeightMetres":0.5,"requiresDirection":true,"directionProperty":"lowerSide","settings":{"lowerSide":{"type":"side","required":true,"values":["left","right"],"default":"right","labelSv":"Lägre sida"}}},
    "106":{"kind":"styled-line","style":"dots","colour":"brown","widthMm":0.18,"styleDiameterMm":0.45,"styleSpacingMm":2,"styleOffsetMm":0.825,"dashMm":[1.65,0.35],"minimumLengthMm":3.65,"minimumDashes":2,"minimumHeightMetres":0.5},
    "107":{"kind":"line","colour":"brown","widthMm":0.25,"minimumLengthMm":1.15},
    "108":{"kind":"dotted-line","colour":"brown","dotDiameterMm":0.25,"gapMm":0.2,"repeatMm":0.45,"minimumLengthMm":0.7,"minimumDots":2},
    "109":{"kind":"point-ring","colour":"brown","diameterMm":0.5,"strokeWidthMm":0.14,"northOriented":false},
    "110":{"kind":"elongated-knoll","colour":"brown","widthMm":0.8,"heightMm":0.4,"northOriented":true},
    "111":{"kind":"small-depression","colour":"brown","widthMm":0.8,"heightMm":0.4,"strokeWidthMm":0.18,"northOriented":true},
    "112":{"kind":"pit","colour":"brown","widthMm":0.7,"heightMm":0.8,"strokeWidthMm":0.18,"northOriented":true},
    "113":{"kind":"pattern-area","pattern":"random-dots","patternColour":"brown","dotDiameterMm":0.2,"patternSpacingMm":0.55,"minimumDots":3,"minimumBoxMm":[0.67,0.67]},
    "114":{"kind":"pattern-area","pattern":"random-dots-dense","patternColour":"brown","dotDiameterMm":0.2,"patternSpacingMm":0.32,"minimumDots":3,"minimumBoxMm":[0.47,0.47]},
    "115":{"kind":"point-star","colour":"brown","widthMm":0.9,"heightMm":0.9,"strokeWidthMm":0.18,"northOriented":true,"requiresDefinition":true},
    "201":{"kind":"cliff","colour":"black","lineWidthMm":0.35,"tagWidthMm":0.12,"tagLengthMm":0.4,"tagSpacingMm":0.5,"minimumLengthMm":0.6,"minimumGapMm":0.25,"requiresDirection":true,"impassable":true,"settings":{"downhillSide":{"type":"side","required":true,"values":["left","right"],"default":"right","labelSv":"Taggarnas nedförssida"}}},
    "202":{"kind":"cliff","colour":"black","lineWidthMm":0.25,"tagWidthMm":0.12,"tagLengthMm":0.25,"tagSpacingMm":0.5,"minimumLengthMm":0.6,"minimumGapMm":0.15,"requiresDirection":true,"settings":{"downhillSide":{"type":"side","required":true,"values":["left","right"],"default":"right","labelSv":"Taggarnas nedförssida"}}},
    "203.1":{"kind":"rocky-pit","colour":"black","widthMm":0.7,"heightMm":0.8,"strokeWidthMm":0.16,"northOriented":true,"settings":{"orientationDegrees":{"type":"angle","default":0,"labelSv":"Riktning mot grottan"}}},
    "203.2":{"kind":"dangerous-pit","colour":"black","innerColour":"white","diameterMm":0.9,"innerDiameterMm":0.35,"northOriented":false},
    "204":{"kind":"point-circle","colour":"black","diameterMm":0.4},
    "205":{"kind":"point-circle","colour":"black","diameterMm":0.6},
    "206":{"kind":"area","fill":"black","minimumWidthMm":0.25,"minimumAreaMm2":0.3,"impassable":true},
    "207":{"kind":"boulder-cluster","colour":"black","widthMm":0.8,"heightMm":0.693,"northOriented":true,"settings":{"sizePercent":{"type":"choice","values":[100,120],"default":100,"labelSv":"Symbolstorlek (%)"}}},
    "208":{"kind":"pattern-area","pattern":"boulders","patternColour":"black","triangleWidthMm":0.8,"triangleHeightMm":0.6,"patternSpacingMm":1,"minimumSymbols":2,"minimumBoxMm":[1.55,0.6]},
    "209":{"kind":"pattern-area","pattern":"boulders-dense","patternColour":"black","triangleWidthMm":0.8,"triangleHeightMm":0.6,"patternSpacingMm":0.55,"minimumSymbols":2,"minimumBoxMm":[1.15,0.6]},
    "210":{"kind":"pattern-area","pattern":"random-dots","patternColour":"black","dotDiameterMm":0.2,"patternSpacingMm":0.52,"minimumDots":3,"minimumBoxMm":[0.67,0.67]},
    "211":{"kind":"pattern-area","pattern":"random-dots-dense","patternColour":"black","dotDiameterMm":0.2,"patternSpacingMm":0.36,"minimumDots":3,"minimumBoxMm":[0.53,0.53]},
    "212":{"kind":"pattern-area","pattern":"random-dots-very-dense","patternColour":"black","dotDiameterMm":0.2,"patternSpacingMm":0.285,"minimumDots":3,"minimumBoxMm":[0.47,0.47]},
    "213":{"kind":"pattern-area","fill":"yellow50","pattern":"sand","patternColour":"black","dotDiameterMm":0.16,"patternSpacingMm":0.45,"patternAngleDeg":45,"minimumBoxMm":[1,1],"northOriented":true},
    "214":{"kind":"area","fill":"black35","minimumBoxMm":[1,1]},
    "215":{"kind":"double-line","colour":"black","lineWidthMm":0.1,"lineCentreGapMm":0.2,"minimumLengthMm":1},
    "301":{"kind":"area","fill":"blue","outline":"black","outlineWidthMm":0.12,"minimumWidthMm":0.3,"minimumBoxMm":[0.55,0.55],"impassable":true},
    "302":{"kind":"area","fill":"blue50","outline":"blue","outlineWidthMm":0.1,"dashMm":[1.25,0.25],"minimumWidthMm":0.3,"minimumBoxMm":[0.7,0.7]},
    "303":{"kind":"waterhole","colour":"blue","widthMm":0.7,"heightMm":0.8,"strokeWidthMm":0.18,"northOriented":true},
    "304":{"kind":"line","colour":"blue","widthMm":0.3,"minimumLengthMm":1},
    "305":{"kind":"line","colour":"blue","widthMm":0.18,"minimumLengthMm":1},
    "306":{"kind":"dashed-line","colour":"blue","widthMm":0.18,"dashMm":[1.25,0.25],"minimumLengthMm":2.75,"minimumDashes":2},
    "307":{"kind":"pattern-area","pattern":"marsh-solid","patternColour":"blue","patternLineWidthMm":0.25,"patternSpacingMm":0.5,"outline":"black","outlineWidthMm":0.12,"minimumWidthMm":0.8,"minimumVisibleLines":2,"impassable":true,"northOriented":true},
    "308":{"kind":"pattern-area","pattern":"marsh-solid","patternColour":"blue","patternLineWidthMm":0.12,"patternSpacingMm":0.3,"minimumBoxMm":[0.5,0.4],"minimumVisibleLines":2,"northOriented":true},
    "309":{"kind":"dotted-line","colour":"blue","dotDiameterMm":0.25,"repeatMm":0.45,"minimumLengthMm":0.7,"minimumDots":2},
    "310":{"kind":"pattern-area","pattern":"marsh-dashed","patternColour":"blue","patternLineWidthMm":0.1,"patternSpacingMm":0.3,"dashMm":[0.9,0.25],"minimumBoxMm":[2,0.7],"northOriented":true},
    "311":{"kind":"point-ring","colour":"blue","diameterMm":0.8,"strokeWidthMm":0.18},
    "312":{"kind":"spring","colour":"blue","widthMm":0.9,"heightMm":0.45,"strokeWidthMm":0.18,"northOriented":false},
    "313":{"kind":"point-cross","colour":"blue","widthMm":0.9,"heightMm":0.9,"strokeWidthMm":0.16,"northOriented":true,"requiresDefinition":true},
    "401":{"kind":"area","fill":"yellow","minimumBoxMm":[0.55,0.55],"minimumWidthMm":0.3},
    "402":{"kind":"pattern-area","fill":"yellow","pattern":"scattered","patternColour":"white","dotDiameterMm":0.4,"patternSpacingMm":0.7,"patternAngleDeg":45,"minimumWidthMm":1.5,"minimumBoxMm":[2,2],"northOriented":true},
    "403":{"kind":"area","fill":"yellow50","minimumBoxMm":[1,1],"minimumWidthMm":0.4},
    "404":{"kind":"pattern-area","fill":"yellow50","pattern":"scattered","patternColour":"white","dotDiameterMm":0.5,"patternSpacingMm":0.8,"patternAngleDeg":45,"minimumWidthMm":1.5,"minimumBoxMm":[2.5,2.5],"northOriented":true},
    "405":{"kind":"area","fill":"white","minimumBoxMm":[1,1]},
    "406":{"kind":"area","fill":"green30","minimumWidthMm":0.4,"minimumBoxMm":[1,1]},
    "407":{"kind":"pattern-area","fill":"white","screenPreview":"green30","pattern":"vertical-green-407","patternColour":"green","patternLineWidthMm":0.12,"patternSpacingMm":0.84,"minimumBoxMm":[1.5,1],"northOriented":true},
    "408":{"kind":"area","fill":"green60","minimumWidthMm":0.3,"minimumBoxMm":[0.7,0.7]},
    "409":{"kind":"pattern-area","fill":"white","screenPreview":"green60","pattern":"vertical-green-409","patternColour":"green","patternLineWidthMm":0.14,"patternSpacingMm":0.42,"minimumBoxMm":[1,1],"northOriented":true},
    "410":{"kind":"area","fill":"green","minimumWidthMm":0.25,"minimumBoxMm":[0.55,0.55]},
    "412":{"kind":"pattern-area","fill":"yellow","pattern":"cultivated","patternColour":"black","dotDiameterMm":0.2,"patternSpacingMm":0.8,"minimumBoxMm":[3,3],"northOriented":true},
    "413":{"kind":"pattern-area","fill":"yellow","pattern":"orchard","patternColour":"green","dotDiameterMm":0.45,"patternSpacingMm":0.8,"minimumBoxMm":[2,2],"northOriented":true,"settings":{"background":{"type":"choice","values":["yellow","yellow50"],"default":"yellow","labelSv":"Bakgrund"},"orientationDegrees":{"type":"angle","default":0,"labelSv":"Planteringsriktning"}}},
    "414":{"kind":"pattern-area","fill":"yellow","pattern":"vineyard","patternColour":"green","patternLineWidthMm":0.2,"patternSpacingMm":0.85,"rowDashMm":[1.3,0.6],"minimumBoxMm":[2,2],"northOriented":true,"requiresOrientation":true,"settings":{"background":{"type":"choice","values":["yellow","yellow50"],"default":"yellow","labelSv":"Bakgrund"},"orientationDegrees":{"type":"angle","default":0,"labelSv":"Planteringsriktning"}}},
    "415":{"kind":"line","colour":"black","widthMm":0.1,"minimumLengthMm":2},
    "416":{"kind":"configurable-boundary","colour":"darkGreen","widthMm":0.14,"dashMm":[0.3,0.2],"dotColour":"black","dotDiameterMm":0.22,"dotRepeatMm":0.45,"minimumLengthMm":1.8,"minimumDashes":4,"settings":{"variant":{"type":"choice","values":["green-dashes","black-dots"],"default":"green-dashes","labelSv":"Utförande"}}},
    "417":{"kind":"masked-ring","colour":"green","maskColour":"white","maskDiameterMm":1.1,"diameterMm":0.9,"strokeWidthMm":0.18},
    "418":{"kind":"point-ring-filled","colour":"green","fill":"white","diameterMm":0.6,"strokeWidthMm":0.2},
    "419":{"kind":"masked-point-cross","colour":"green","maskColour":"white","widthMm":0.9,"heightMm":0.9,"maskWidthMm":1.08,"maskHeightMm":1.08,"strokeWidthMm":0.18,"maskStrokeWidthMm":0.36,"northOriented":true,"requiresDefinition":true},
    "501":{"kind":"area","fill":"brown50","outline":"black","outlineWidthMm":0.1,"minimumBoxMm":[1,1]},
    "502":{"kind":"cased-line","fill":"brown50","outline":"black","outlineWidthMm":0.14,"minimumInnerWidthMm":0.3},
    "503":{"kind":"line","colour":"black","widthMm":0.35,"minimumLengthMm":0.6},
    "504":{"kind":"dashed-line","colour":"black","widthMm":0.25,"dashMm":[3,0.35],"minimumLengthMm":6.25,"minimumDashes":2},
    "505":{"kind":"dashed-line","colour":"black","widthMm":0.25,"dashMm":[2,0.25],"minimumLengthMm":4.25,"minimumDashes":2},
    "506":{"kind":"dashed-line","colour":"black","widthMm":0.18,"dashMm":[1,0.25],"minimumLengthMm":2.25,"minimumDashes":2},
    "507":{"kind":"dashed-line","colour":"black","widthMm":0.18,"dashMm":[1,0.25,1,0.8],"minimumLengthMm":5.3,"minimumDashes":4},
    "508":{"kind":"opening-line","colour":"black","widthMm":0.14,"dashMm":[2,0.25],"backgroundWidthMm":0.45,"minimumLengthMm":3.25,"minimumDashes":2,"settings":{"runnability":{"type":"choice","values":["surrounding","better","normal","slow","walk"],"default":"surrounding","labelSv":"Löpbarhet"}}},
    "509":{"kind":"railway","colour":"black","innerColour":"white","widthMm":0.35,"innerWidthMm":0.1,"dashMm":[1,0.5],"minimumLengthMm":4,"minimumDashes":2},
    "510":{"kind":"line-with-supports","colour":"black","widthMm":0.14,"supportWidthMm":0.3,"supportStrokeMm":0.14,"minimumLengthMm":5,"settings":{"supports":{"type":"line-supports","exactPosition":true,"defaultSupportType":"pole","labelSv":"Stolpar"}}},
    "511":{"kind":"double-line-with-supports","colour":"black","lineWidthMm":0.14,"lineCentreGapMm":0.4,"supportOverhangMm":0.3,"supportWidthMm":1.14,"supportStrokeMm":0.2,"largeSupportSizeMm":0.8,"largeSupportStrokeMm":0.2,"settings":{"supports":{"type":"line-supports","exactPosition":true,"defaultSupportType":"tower","allowLargeMast":true,"labelSv":"Master"}}},
    "512":{"kind":"bridge-tunnel","colour":"black","widthMm":0.18,"tagWidthMm":0.18,"tagLengthMm":0.5,"tagAngleDeg":60,"minimumLengthMm":0.4},
    "513.1":{"kind":"styled-line","style":"dots","colour":"black","widthMm":0.14,"styleDiameterMm":0.4,"styleSpacingMm":2,"endGapMm":0.8,"minimumLengthMm":1.4,"minimumHeightMetres":1},
    "513.2":{"kind":"styled-line","style":"half-dots","colour":"black","widthMm":0.14,"styleDiameterMm":0.4,"styleSpacingMm":1,"styleOffsetMm":0.8,"sideOffsetMm":0.05,"endGapMm":0.6,"minimumLengthMm":1.4,"minimumHeightMetres":0.5,"requiresDirection":true,"directionProperty":"lowerSide","settings":{"lowerSide":{"type":"side","required":true,"values":["left","right"],"default":"right","labelSv":"Lägre sida"}}},
    "514":{"kind":"styled-line","style":"dots","colour":"black","widthMm":0.14,"styleDiameterMm":0.4,"styleSpacingMm":2,"styleOffsetMm":0.825,"dashMm":[1.65,0.35],"minimumLengthMm":3.65,"minimumDashes":2,"minimumHeightMetres":0.5},
    "515":{"kind":"styled-line","style":"grouped-dots","colour":"black","widthMm":0.25,"styleDiameterMm":0.6,"groupSpacingMm":3,"withinGroupSpacingMm":0.8,"groupOffsetMm":1.5,"minimumLengthMm":3,"minimumHeightMetres":1.5,"impassable":true},
    "516":{"kind":"styled-line","style":"fence-tags","colour":"black","widthMm":0.14,"tagLengthMm":0.4,"tagWidthMm":0.14,"tagAngleDeg":60,"styleSpacingMm":2,"minimumLengthMm":1.5,"requiresDirection":true,"directionProperty":"tagSide","settings":{"tagSide":{"type":"side","required":true,"values":["left","right"],"default":"right","labelSv":"Taggarnas sida"}}},
    "517":{"kind":"styled-line","style":"fence-tags","colour":"black","widthMm":0.14,"tagLengthMm":0.4,"tagWidthMm":0.14,"tagAngleDeg":60,"styleSpacingMm":2,"styleOffsetMm":0.825,"dashMm":[1.65,0.35],"minimumLengthMm":3.65,"minimumDashes":2,"requiresDirection":true,"directionProperty":"tagSide","settings":{"tagSide":{"type":"side","required":true,"values":["left","right"],"default":"right","labelSv":"Taggarnas sida"}}},
    "518":{"kind":"styled-line","style":"grouped-fence-tags","colour":"black","widthMm":0.25,"tagLengthMm":0.4,"tagWidthMm":0.14,"tagAngleDeg":60,"groupSpacingMm":2.5,"withinGroupSpacingMm":0.6,"groupOffsetMm":1,"minimumLengthMm":2,"minimumHeightMetres":1.5,"impassable":true,"requiresDirection":true,"directionProperty":"tagSide","settings":{"tagSide":{"type":"side","required":true,"values":["left","right"],"default":"right","labelSv":"Taggarnas sida"}}},
    "519":{"kind":"crossing-point","colour":"black","widthMm":0.78,"heightMm":1,"barLengthMm":1,"barSpacingMm":0.6,"strokeWidthMm":0.18,"maskWidthMm":0.6,"settings":{"breakBarrier":{"type":"boolean","default":true,"labelSv":"Bryt barriärlinjen"}}},
    "520":{"kind":"area","fill":"yellowGreen50","outline":"black","outlineWidthMm":0.18,"outlineConditional":"clear","minimumBoxMm":[1,1],"impassable":true,"pathWhiteOverlapMm":0.15},
    "521":{"kind":"area","fill":"black","largeFill":"black50","largeThresholdMetres":75,"minimumBoxMm":[0.5,0.5],"minimumPassageMm":0.4,"impassable":true},
    "522":{"kind":"area","fill":"black20","outline":"black","outlineWidthMm":0.1,"minimumBoxMm":[0.6,0.6],"minimumWidthMm":0.4},
    "523":{"kind":"outline-area","outline":"black","outlineWidthMm":0.16,"dashMm":[0.5,0.25],"minimumBoxMm":[0.8,0.8],"outsideMeasure":true,"solidBelowMinimum":true},
    "524":{"kind":"high-tower","colour":"black","diameterMm":0.8,"innerDiameterMm":0.3,"strokeWidthMm":0.16,"northOriented":true},
    "525":{"kind":"small-tower","colour":"black","widthMm":1,"heightMm":1,"strokeWidthMm":0.16,"northOriented":true},
    "526":{"kind":"cairn","colour":"black","diameterMm":0.8,"innerDiameterMm":0.14,"strokeWidthMm":0.16,"minimumHeightMetres":0.5},
    "527":{"kind":"fodder-rack","colour":"black","widthMm":0.9,"heightMm":0.9,"roofRiseMm":0.354,"strokeWidthMm":0.16,"northOriented":true},
    "528":{"kind":"styled-line","style":"chevrons","colour":"black","widthMm":0.14,"tagLengthMm":0.4,"tagWidthMm":0.14,"tagAngleDeg":45,"styleSpacingMm":2,"styleOffsetMm":1,"minimumLengthMm":1.5,"requiresDefinition":true},
    "529":{"kind":"styled-line","style":"grouped-chevrons","colour":"black","widthMm":0.25,"tagLengthMm":0.4,"tagWidthMm":0.14,"tagAngleDeg":45,"groupSpacingMm":2,"groupOffsetMm":1,"withinGroupSpacingMm":0.6,"minimumLengthMm":2,"impassable":true,"requiresDefinition":true},
    "530":{"kind":"point-ring","colour":"black","diameterMm":0.8,"strokeWidthMm":0.16,"requiresDefinition":true},
    "531":{"kind":"point-cross","colour":"black","widthMm":0.8,"heightMm":0.8,"strokeWidthMm":0.16,"northOriented":true,"requiresDefinition":true},
    "532":{"kind":"stairway","colour":"black","railWidthMm":0.1,"innerWidthMm":0.4,"stepWidthMm":0.1,"stepSpacingMm":0.4,"minimumLengthMm":1.2,"minimumSteps":3},
    "601":{"kind":"north-line","colour":"black","widthMm":0.1,"spacingGroundMetres":300,"northOriented":true},
    "602":{"kind":"registration-mark","colour":"black","widthMm":4,"heightMm":4,"strokeWidthMm":0.1,"allPrintingColours":true},
    "603":{"kind":"elevation-text","colour":"black","dotDiameterMm":0.3,"textHeightMm":1.5,"widthMm":4,"heightMm":1.8},
    "701":{"kind":"course-start","colour":"purpleLower","widthMm":6,"heightMm":5.196,"strokeWidthMm":0.35,"requiresOrientation":true,"settings":{"orientationDegrees":{"type":"angle","default":0,"labelSv":"Riktning mot första kontrollen"}}},
    "702":{"kind":"map-issue-point","colour":"purpleUpper","widthMm":0.6,"heightMm":2.5,"strokeWidthMm":0.6},
    "703":{"kind":"control-circle","colour":"purpleLower","diameterMm":5,"strokeWidthMm":0.35},
    "704":{"kind":"course-number","colour":"purpleLower","textHeightMm":4,"widthMm":6,"heightMm":4},
    "705":{"kind":"line","colour":"purpleLower","widthMm":0.35},
    "706":{"kind":"course-finish","colour":"purpleLower","diameterMm":6,"innerDiameterMm":4,"strokeWidthMm":0.35},
    "707":{"kind":"dashed-line","colour":"purpleUpper","widthMm":0.35,"dashMm":[2,0.5],"minimumLengthMm":4.5,"minimumDashes":2},
    "708":{"kind":"line","colour":"purpleLower","widthMm":0.7,"minimumLengthMm":1},
    "709":{"kind":"pattern-area","pattern":"forbidden-crosshatch","patternColour":"purpleUpper","patternLineWidthMm":0.2,"patternSpacingMm":1.2,"outline":"purpleUpper","outlineWidthMm":0.25,"minimumWidthMm":3,"minimumBoxMm":[3,3],"northOriented":true},
    "710":{"kind":"crossing-gate","colour":"purpleLower","widthMm":0.6,"heightMm":3,"strokeWidthMm":0.35,"requiresOrientation":true,"settings":{"orientationDegrees":{"type":"angle","default":0,"labelSv":"Passagens riktning"}}},
    "711":{"kind":"styled-line","style":"course-crosses","colour":"purpleUpper","widthMm":0.35,"styleWidthMm":3,"styleHeightMm":3,"styleSpacingMm":5,"minimumLengthMm":6,"minimumSymbols":2},
    "712":{"kind":"first-aid","colour":"purpleLower","widthMm":4,"heightMm":4,"barWidthMm":1.33},
    "713":{"kind":"refreshment","colour":"purpleLower","widthMm":3.5,"heightMm":3.5,"baseWidthMm":2.1,"strokeWidthMm":0.4},
    "715":{"kind":"map-exchange-start","colour":"purpleLower","diameterMm":6,"strokeWidthMm":0.35,"requiresOrientation":true,"settings":{"orientationDegrees":{"type":"angle","default":0,"labelSv":"Riktning mot nästa kontroll"}}}
  },
  "symbols": {
    "101": {"nameSv":"Höjdkurva","nameEn":"Contour","geometry":["LineString"],"bindingRules":["5 m eller 2,5 m i genomgående flack terräng"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "102": {"nameSv":"Stödkurva","nameEn":"Index contour","geometry":["LineString"],"bindingRules":["Var femte höjdkurva"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "103": {"nameSv":"Hjälpkurva","nameEn":"Form line","geometry":["LineString","MultiLineString"],"bindingRules":["Endast när terrängformen inte kan visas fullständigt med vanliga höjdkurvor","Minst två streck för öppen hjälpkurva"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "104": {"nameSv":"Skärning","nameEn":"Earth bank","geometry":["LineString","MultiLineString"],"bindingRules":["Tydlig nivåförändring, minst 1 m hög","Taggarna visar den horisontella utsträckningen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "105.1": {"nameSv":"Jordvall","nameEn":"Earth wall","geometry":["LineString","MultiLineString"],"bindingRules":["Tydlig jordvall, minst 1 m hög"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "105.2": {"nameSv":"Stödmur av jord","nameEn":"Retaining earth wall","geometry":["LineString","MultiLineString"],"bindingRules":["Tydlig människoskapad jordkant, minst 0,5 m hög","Halvpunkter mot lägre sida"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "106": {"nameSv":"Otydlig jordvall","nameEn":"Ruined earth wall","geometry":["LineString","MultiLineString"],"bindingRules":["Otydlig eller raserad jordvall, minst 0,5 m hög"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "107": {"nameSv":"Erosionsfåra","nameEn":"Erosion gully","geometry":["LineString","MultiLineString"],"bindingRules":["Minst 1 m djup och för liten för skärningssymbolen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "108": {"nameSv":"Liten fåra eller torrt dike","nameEn":"Small erosion gully","geometry":["LineString"],"bindingRules":["Torrt erosionsdike som är för smalt för symbol 107"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "109": {"nameSv":"Punkthöjd","nameEn":"Small knoll","geometry":["Point"],"bindingRules":["Distinkt kulle som inte kan visas skalenligt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "110": {"nameSv":"Avlång punkthöjd","nameEn":"Small elongated knoll","geometry":["Point"],"bindingRules":["Distinkt långsträckt kulle, minst 1 m hög","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "111": {"nameSv":"Liten grop","nameEn":"Small depression","geometry":["Point"],"bindingRules":["Sänka utan branta sidor, minst 1 m djup och 2 m bred","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "112": {"nameSv":"Liten grop med branta sidor","nameEn":"Pit","geometry":["Point"],"bindingRules":["Distinkt grop som inte kan visas skalenligt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "113": {"nameSv":"Småkuperad terräng","nameEn":"Broken ground","geometry":["Polygon","MultiPolygon"],"bindingRules":["Minst tre oregelbundet placerade punkter","Liten påverkan på löpbarheten"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "114": {"nameSv":"Mycket småkuperad terräng","nameEn":"Very broken ground","geometry":["Polygon","MultiPolygon"],"bindingRules":["Minst tre oregelbundet placerade punkter","Påverkar löpbarheten"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "115": {"nameSv":"Tydligt terrängföremål","nameEn":"Prominent landform feature","geometry":["Point"],"bindingRules":["Betydelsen ska redovisas i teckenförklaringen","Kolbotten redovisas med denna symbol enligt svenskt förtydligande"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "201": {"nameSv":"Opasserbar brant","nameEn":"Impassable cliff","geometry":["LineString"],"bindingRules":["Farlig eller omöjlig att passera"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "202": {"nameSv":"Passerbar brant","nameEn":"Cliff","geometry":["LineString"],"bindingRules":["Passerbar brant"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "203.1": {"nameSv":"Stenig grop eller grotta","nameEn":"Rocky pit or cave","geometry":["Point"],"bindingRules":["Stengrop, hål, grotta eller gruvschakt, minst 1 m djupt","Grottsymbolen riktas in mot grottan"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "203.2": {"nameSv":"Farlig grop","nameEn":"Dangerous pit","geometry":["Point"],"bindingRules":["Mycket farlig grop, lodrätt schakt eller avgrund"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "204": {"nameSv":"Sten","nameEn":"Boulder","geometry":["Point"],"bindingRules":["Distinkt sten, normalt över 1 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "205": {"nameSv":"Stor sten","nameEn":"Large boulder","geometry":["Point"],"bindingRules":["Särskilt stor eller prominent sten, normalt över 2 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "206": {"nameSv":"Gigantisk sten eller stenpelare","nameEn":"Gigantic boulder or rock pillar","geometry":["Polygon","MultiPolygon"],"bindingRules":["Ritas skalenligt i planform","Minsta bredd 0,25 mm och minsta area 0,3 mm²"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "207": {"nameSv":"Grupp av stenar","nameEn":"Boulder cluster","geometry":["Point"],"bindingRules":["Tydlig grupp av tätt liggande stenar som inte kan redovisas var för sig","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "208": {"nameSv":"Blockterräng","nameEn":"Boulder field","geometry":["Polygon","MultiPolygon"],"bindingRules":["Minst två oregelbundet roterade trianglar","Löpbarheten normalt opåverkad"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "209": {"nameSv":"Tät blockterräng","nameEn":"Dense boulder field","geometry":["Polygon","MultiPolygon"],"bindingRules":["Minst två oregelbundet roterade trianglar","Nedsatt löpbarhet"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "210": {"nameSv":"Stenig mark, löphindrande","nameEn":"Stony ground, slow running","geometry":["Polygon","MultiPolygon"],"bindingRules":["Löpbarhet cirka 60–80 %","Minst tre oregelbundet placerade punkter"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "211": {"nameSv":"Stenig mark, svårlöpt","nameEn":"Stony ground, walk","geometry":["Polygon","MultiPolygon"],"bindingRules":["Löpbarhet cirka 20–60 %","Minst tre oregelbundet placerade punkter"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "212": {"nameSv":"Stenig mark, svårframkomlig","nameEn":"Stony ground, fight","geometry":["Polygon","MultiPolygon"],"bindingRules":["Löpbarhet under 20 %","Minst tre oregelbundet placerade punkter"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "213": {"nameSv":"Sandområde","nameEn":"Sandy ground","geometry":["Polygon","MultiPolygon"],"bindingRules":["Mjuk sandig mark med löpbarhet under 80 %","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "214": {"nameSv":"Berg i dagen","nameEn":"Bare rock","geometry":["Polygon","MultiPolygon"],"bindingRules":["Löpbar bergyta utan jord eller vegetation"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "215": {"nameSv":"Värn","nameEn":"Trench","geometry":["LineString","MultiLineString"],"bindingRules":["Bergsskreva eller konstgjort värn, normalt minst 1 m djupt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "301": {"nameSv":"Opasserbar vattenyta","nameEn":"Uncrossable body of water","geometry":["Polygon","MultiPolygon"],"bindingRules":["Djupt eller farligt vatten"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "302": {"nameSv":"Grund vattenyta","nameEn":"Shallow body of water","geometry":["Polygon","MultiPolygon"],"bindingRules":["Mindre än 0,5 m djup och passerbar"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "303": {"nameSv":"Vattenhål","nameEn":"Waterhole","geometry":["Point"],"bindingRules":["Litet tydligt vattenobjekt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "304": {"nameSv":"Passerbart vattendrag","nameEn":"Crossable watercourse","geometry":["LineString","MultiLineString"],"bindingRules":["Bredare än 2 m och passerbart"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "305": {"nameSv":"Passerbart litet vattendrag","nameEn":"Small crossable watercourse","geometry":["LineString","MultiLineString"],"bindingRules":["Smalare än 2 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "306": {"nameSv":"Mindre vattendrag","nameEn":"Minor/seasonal water channel","geometry":["LineString","MultiLineString"],"bindingRules":["Litet, periodiskt eller otydligt vattenflöde"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "307": {"nameSv":"Opasserbar sankmark","nameEn":"Uncrossable marsh","geometry":["Polygon","MultiPolygon"],"bindingRules":["Farlig eller ej passerbar sankmark"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "308": {"nameSv":"Sankmark","nameEn":"Marsh","geometry":["Polygon","MultiPolygon"],"bindingRules":["Passerbar sankmark"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "309": {"nameSv":"Smal sankmark","nameEn":"Narrow marsh","geometry":["LineString","MultiLineString"],"bindingRules":["Sankmark som är för smal för ytsymbol"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "310": {"nameSv":"Otydlig sankmark","nameEn":"Indistinct marsh","geometry":["Polygon","MultiPolygon"],"bindingRules":["Svag eller periodisk sankmark"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "311": {"nameSv":"Brunn, fontän eller vattentank","nameEn":"Well, fountain or water tank","geometry":["Point"],"bindingRules":["Distinkt vatteninstallation"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "312": {"nameSv":"Källa","nameEn":"Spring","geometry":["Point"],"bindingRules":["Distinkt källa"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "313": {"nameSv":"Tydligt vattenföremål","nameEn":"Prominent water feature","geometry":["Point"],"bindingRules":["Betydelsen ska förklaras på kartan"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "401": {"nameSv":"Öppen lättlöpt mark","nameEn":"Open land","geometry":["Polygon","MultiPolygon"],"bindingRules":["Löpbar öppen mark"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "402": {"nameSv":"Öppen lättlöpt mark med spridda träd","nameEn":"Open land with scattered trees","geometry":["Polygon","MultiPolygon"],"bindingRules":["Löpbar öppen mark med spridda träd"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "403": {"nameSv":"Öppen mark med normal löpbarhet","nameEn":"Rough open land","geometry":["Polygon","MultiPolygon"],"bindingRules":["Öppen mark med sämre löpbarhet"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "404": {"nameSv":"Öppen mark med normal löpbarhet och spridda träd","nameEn":"Rough open land with scattered trees","geometry":["Polygon","MultiPolygon"],"bindingRules":["Klassificera efter löpbarhet och trädtäthet, inte markanvändningens namn"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "405": {"nameSv":"Skog","nameEn":"Forest","geometry":["Polygon","MultiPolygon"],"bindingRules":["Normalt lättlöpt skog för terrängtypen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "406": {"nameSv":"Skog, löphindrande","nameEn":"Vegetation: slow running","geometry":["Polygon","MultiPolygon"],"bindingRules":["Cirka 60–80 % av normal löphastighet","Låg sikt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "407": {"nameSv":"Undervegetation, löphindrande, god sikt","nameEn":"Vegetation: slow running, good visibility","geometry":["Polygon","MultiPolygon"],"bindingRules":["Cirka 60–80 % av normal löphastighet","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "408": {"nameSv":"Skog, svårlöpt","nameEn":"Vegetation: walk","geometry":["Polygon","MultiPolygon"],"bindingRules":["Vegetation som normalt passeras gående"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "409": {"nameSv":"Undervegetation, svårlöpt, god sikt","nameEn":"Vegetation: walk, good visibility","geometry":["Polygon","MultiPolygon"],"bindingRules":["Cirka 20–60 % av normal löphastighet","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "410": {"nameSv":"Skog, svårframkomlig","nameEn":"Vegetation: fight","geometry":["Polygon","MultiPolygon"],"bindingRules":["0–20 % av normal löphastighet"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "412": {"nameSv":"Odlad mark","nameEn":"Cultivated land","geometry":["Polygon","MultiPolygon"],"bindingRules":["Tillträdesförbud anges separat"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "413": {"nameSv":"Fruktodling","nameEn":"Orchard","geometry":["Polygon","MultiPolygon"],"bindingRules":["Regelbundet planterade träd eller buskar","Punktrader får roteras till planteringsriktningen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "414": {"nameSv":"Vingård eller liknande","nameEn":"Vineyard or similar","geometry":["Polygon","MultiPolygon"],"bindingRules":["Täta plantrader","Linjer ska roteras till planteringsriktningen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "415": {"nameSv":"Exakt begränsningslinje","nameEn":"Distinct cultivation boundary","geometry":["LineString","MultiLineString"],"bindingRules":["Tydlig gräns för odlad mark när annat linjeobjekt saknas"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "416": {"nameSv":"Tydlig beståndsgräns","nameEn":"Distinct vegetation boundary","geometry":["LineString","MultiLineString"],"bindingRules":["Endast ett av utförandena svart punktlinje eller streckad mörkgrön linje ska användas på kartan"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "417": {"nameSv":"Tydligt stort träd","nameEn":"Prominent large tree","geometry":["Point"],"bindingRules":["Mycket stort enskilt träd som tydligt avviker från omgivningen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "418": {"nameSv":"Tydligt träd eller buske","nameEn":"Prominent bush or tree","geometry":["Point"],"bindingRules":["Buske eller mindre enskilt träd som tydligt avviker","Används sparsamt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "419": {"nameSv":"Tydligt vegetationsföremål","nameEn":"Prominent vegetation feature","geometry":["Point"],"bindingRules":["Betydelsen ska förklaras på kartan","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "501": {"nameSv":"Belagd yta","nameEn":"Paved area","geometry":["Polygon","MultiPolygon"],"bindingRules":["Fast yta; minst 1 × 1 mm i tryck"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "502": {"nameSv":"Bred väg","nameEn":"Wide road","geometry":["LineString","MultiLineString"],"bindingRules":["Allvädersväg bredare än 5 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "503": {"nameSv":"Väg","nameEn":"Road","geometry":["LineString","MultiLineString"],"bindingRules":["Allvädersväg 3–5 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "504": {"nameSv":"Körväg","nameEn":"Vehicle track","geometry":["LineString","MultiLineString"],"bindingRules":["Fordonsspår under 3 m; materialet avgör inte symbolen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "505": {"nameSv":"Stor stig","nameEn":"Footpath","geometry":["LineString","MultiLineString"],"bindingRules":["Tydlig stig"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "506": {"nameSv":"Liten stig","nameEn":"Small footpath","geometry":["LineString","MultiLineString"],"bindingRules":["Mindre men tydlig stig"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "507": {"nameSv":"Liten otydlig stig","nameEn":"Less distinct small footpath","geometry":["LineString","MultiLineString"],"bindingRules":["Svårföljd liten stig"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "508": {"nameSv":"Rågång, drivningsväg eller annan smal öppning","nameEn":"Narrow ride","geometry":["LineString","MultiLineString"],"bindingRules":["Smal linjär öppning utan tydlig löpbar stig","Bakgrundslinjen visar löpbarhet"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "509": {"nameSv":"Järnväg","nameEn":"Railway","geometry":["LineString","MultiLineString"],"bindingRules":["Förbjuden passage anges separat"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "510": {"nameSv":"Kraftledning, linbana eller skidlift","nameEn":"Power line, cableway or skilift","geometry":["LineString","MultiLineString","Point"],"bindingRules":["Stödmarkeringar ska motsvara exakta stolp- och mastlägen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "511": {"nameSv":"Större kraftledning","nameEn":"Major power line","geometry":["LineString","MultiLineString","Point"],"bindingRules":["Dubbel linje och exakta mastlägen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "512": {"nameSv":"Bro/tunnel","nameEn":"Bridge/tunnel","geometry":["LineString","MultiLineString"],"bindingRules":["Broar och passerbara tunnlar redovisas med samma symbol","Kortaste baslinje 0,4 mm"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "513.1": {"nameSv":"Mur","nameEn":"Wall","geometry":["LineString","MultiLineString"],"bindingRules":["Betydande mur, normalt minst 1 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "513.2": {"nameSv":"Stödmur/terrass","nameEn":"Retaining wall","geometry":["LineString","MultiLineString"],"bindingRules":["Halvpunkter ska peka mot den lägre sidan","Minst 0,5 m hög"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "514": {"nameSv":"Otydlig mur","nameEn":"Ruined wall","geometry":["LineString","MultiLineString"],"bindingRules":["Raserad eller mindre tydlig mur, minst 0,5 m hög"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "515": {"nameSv":"Opasserbar mur","nameEn":"Impassable wall","geometry":["LineString","MultiLineString"],"bindingRules":["Normalt högre än 1,5 m och omöjlig att passera"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "516": {"nameSv":"Stängsel","nameEn":"Fence","geometry":["LineString","MultiLineString"],"bindingRules":["Betydande passerbart staket"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "517": {"nameSv":"Raserat stängsel","nameEn":"Ruined fence","geometry":["LineString","MultiLineString"],"bindingRules":["Raserat eller mindre tydligt staket"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "518": {"nameSv":"Opasserbart stängsel","nameEn":"Impassable fence","geometry":["LineString","MultiLineString"],"bindingRules":["Normalt högre än 1,5 m och omöjligt att passera"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "519": {"nameSv":"Genomgång","nameEn":"Crossing point","geometry":["Point"],"bindingRules":["Port, stätta eller annan passage genom en linjär barriär"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "520": {"nameSv":"Förbjudet område","nameEn":"Area that shall not be entered","geometry":["Polygon","MultiPolygon"],"bindingRules":["Får inte beträdas; intern kartinformation ska begränsas enligt normen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "521": {"nameSv":"Byggnad","nameEn":"Building","geometry":["Polygon","MultiPolygon"],"bindingRules":["Ritas skalenligt och generaliseras enligt minimimått"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "522": {"nameSv":"Skärmtak","nameEn":"Canopy","geometry":["Polygon","MultiPolygon"],"bindingRules":["Tillgänglig och löpbar yta under tak","Minsta inre bredd 0,4 mm"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "523": {"nameSv":"Ruin","nameEn":"Ruin","geometry":["LineString","MultiLineString","Polygon","MultiPolygon"],"bindingRules":["Grundplanen visas skalenligt","Minsta yttermått 0,8 × 0,8 mm"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "524": {"nameSv":"Högt torn","nameEn":"High tower","geometry":["Point"],"bindingRules":["Prominent högt torn eller mast"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "525": {"nameSv":"Litet torn","nameEn":"Small tower","geometry":["Point"],"bindingRules":["Tydligt litet torn, upphöjd plattform eller jakttorn","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "526": {"nameSv":"Röse","nameEn":"Cairn","geometry":["Point"],"bindingRules":["Prominent röse, minnessten, gränssten eller triangelpunkt","Minst 0,5 m hög"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "527": {"nameSv":"Foderhäck","nameEn":"Fodder rack","geometry":["Point"],"bindingRules":["Fristående foderhäck","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "528": {"nameSv":"Tydligt linjeföremål","nameEn":"Prominent line feature","geometry":["LineString","MultiLineString"],"bindingRules":["Framträdande människoskapat linjeobjekt","Betydelsen ska förklaras på kartan"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "529": {"nameSv":"Tydligt opasserbart linjeföremål","nameEn":"Prominent uncrossable line feature","geometry":["LineString","MultiLineString"],"bindingRules":["Framträdande människoskapat linjeobjekt som inte får passeras","Betydelsen ska förklaras på kartan"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "530": {"nameSv":"Tydligt människoframställt föremål – ring","nameEn":"Prominent man-made feature – ring","geometry":["Point"],"bindingRules":["Framträdande människoskapat punktobjekt","Betydelsen ska förklaras på kartan"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "531": {"nameSv":"Tydligt människoframställt föremål – x","nameEn":"Prominent man-made feature – x","geometry":["Point"],"bindingRules":["Framträdande människoskapat punktobjekt","Betydelsen ska förklaras på kartan","Symbolen orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "532": {"nameSv":"Trappa","nameEn":"Stairway","geometry":["LineString","MultiLineString"],"bindingRules":["Tydlig trappa genom brant terräng eller över opasserbart objekt","Minst tre grafiska steg"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "601": {"nameSv":"Magnetisk nordlinje","nameEn":"Magnetic north line","geometry":["LineString","MultiLineString"],"bindingRules":["Parallell med papperskanten mot magnetiskt norr","300 m markavstånd vid 1:15 000"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "602": {"nameSv":"Passmärken","nameEn":"Registration marks","geometry":["Point"],"bindingRules":["Minst tre märken får placeras i kartans hörn","Trycks i alla tryckfärger"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "603": {"nameSv":"Höjdangivelse","nameEn":"Spot height","geometry":["Point"],"bindingRules":["Höjd i närmaste meter","Vattenytor anges utan punkt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "701": {"nameSv":"Start","nameEn":"Start","geometry":["Point"],"bindingRules":["Triangelns mittpunkt är startläget","Triangeln pekar mot första kontrollen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "702": {"nameSv":"Kartutdelningsplats","nameEn":"Map issue point","geometry":["Point"],"bindingRules":["Används när det är snitsling till startpunkten"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "703": {"nameSv":"Kontroller","nameEn":"Control points","geometry":["Point"],"bindingRules":["Ringens mittpunkt anger kontrollens exakta läge"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "704": {"nameSv":"Kontrollsiffror","nameEn":"Control numbers","geometry":["Point"],"bindingRules":["Arial 4,0 mm, inte fet eller kursiv","Orienteras mot norr"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "705": {"nameSv":"Sammanbindningslinjer","nameEn":"Course lines","geometry":["LineString","MultiLineString"],"bindingRules":["Rak linje mellan kontroller i ordningsföljd","Uppehåll bör göras för läsbarhet"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "706": {"nameSv":"Mål","nameEn":"Finish","geometry":["Point"],"bindingRules":["Dubbelring markerar målet"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "707": {"nameSv":"Snitslade delar","nameEn":"Marked route","geometry":["LineString","MultiLineString"],"bindingRules":["Obligatorisk markerad rutt","Minst två streck"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "708": {"nameSv":"Gräns förbjuden att passera","nameEn":"Out-of-bounds boundary","geometry":["LineString","MultiLineString"],"bindingRules":["Får inte passeras eller korsas under tävling"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "709": {"nameSv":"Förbjudet område","nameEn":"Out-of-bounds area","geometry":["Polygon","MultiPolygon"],"bindingRules":["Får inte beträdas","Minsta bredd och minsta yta 3 mm"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "710": {"nameSv":"Passeringspunkt","nameEn":"Crossing point","geometry":["Point","LineString"],"bindingRules":["Två utåtböjda linjer visar en tillåten passage","Visas i verklig längd"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "711": {"nameSv":"Förbjuden väg","nameEn":"Forbidden route","geometry":["LineString","MultiLineString"],"bindingRules":["Vägen får korsas men inte följas","Minst två kryss"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "712": {"nameSv":"Första hjälpen-plats","nameEn":"First aid post","geometry":["Point"],"bindingRules":["Plats för första hjälpen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "713": {"nameSv":"Vätskeplats","nameEn":"Refreshment point","geometry":["Point"],"bindingRules":["Vätskeplats som inte ligger vid kontroll"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "715": {"nameSv":"Startpunkt efter kartbyte","nameEn":"Map exchange start point","geometry":["Point"],"bindingRules":["Triangeln pekar mot nästa kontroll"],"supportStatus":"partial","rendererStatus":"semantic-match"}
  },
  "manualTypes": {
    "form_line": {"category":"line","geometry":"LineString","symbol":"103","nameSv":"Hjälpkurva","selectable":true,"publishable":true},
    "earth_bank": {"category":"line","geometry":"LineString","symbol":"104","nameSv":"Skärning","selectable":true,"publishable":true},
    "earth_wall": {"category":"line","geometry":"LineString","symbol":"105.1","nameSv":"Jordvall","selectable":true,"publishable":true},
    "retaining_earth_wall": {"category":"line","geometry":"LineString","symbol":"105.2","nameSv":"Stödmur av jord","selectable":true,"publishable":true},
    "ruined_earth_wall": {"category":"line","geometry":"LineString","symbol":"106","nameSv":"Otydlig jordvall","selectable":true,"publishable":true},
    "erosion_gully": {"category":"line","geometry":"LineString","symbol":"107","nameSv":"Erosionsfåra","selectable":true,"publishable":true},
    "broken_ground": {"category":"area","geometry":"Polygon","symbol":"113","nameSv":"Småkuperad terräng","selectable":true,"publishable":true},
    "very_broken_ground": {"category":"area","geometry":"Polygon","symbol":"114","nameSv":"Mycket småkuperad terräng","selectable":true,"publishable":true},
    "prominent_landform": {"category":"point","geometry":"Point","symbol":"115","nameSv":"Tydligt terrängföremål","selectable":true,"publishable":true},
    "boulder_field": {"category":"area","geometry":"Polygon","symbol":"208","nameSv":"Blockterräng","selectable":true,"publishable":true},
    "dense_boulder_field": {"category":"area","geometry":"Polygon","symbol":"209","nameSv":"Tät blockterräng","selectable":true,"publishable":true},
    "stony_ground_slow": {"category":"area","geometry":"Polygon","symbol":"210","nameSv":"Stenig mark, löphindrande","selectable":true,"publishable":true},
    "stony_ground_walk": {"category":"area","geometry":"Polygon","symbol":"211","nameSv":"Stenig mark, svårlöpt","selectable":true,"publishable":true},
    "stony_ground_fight": {"category":"area","geometry":"Polygon","symbol":"212","nameSv":"Stenig mark, svårframkomlig","selectable":true,"publishable":true},
    "sandy_ground": {"category":"area","geometry":"Polygon","symbol":"213","nameSv":"Sandområde","selectable":true,"publishable":true},
    "bare_rock": {"category":"area","geometry":"Polygon","symbol":"214","nameSv":"Berg i dagen","selectable":true,"publishable":true},
    "trench": {"category":"line","geometry":"LineString","symbol":"215","nameSv":"Värn","selectable":true,"publishable":true},
    "orchard": {"category":"area","geometry":"Polygon","symbol":"413","nameSv":"Fruktodling","selectable":true,"publishable":true},
    "vineyard": {"category":"area","geometry":"Polygon","symbol":"414","nameSv":"Vingård eller liknande","selectable":true,"publishable":true},
    "vegetation_boundary": {"category":"line","geometry":"LineString","symbol":"416","nameSv":"Tydlig beståndsgräns","selectable":true,"publishable":true},
    "narrow_ride": {"category":"line","geometry":"LineString","symbol":"508","nameSv":"Rågång, drivningsväg eller annan smal öppning","selectable":true,"publishable":true},
    "bridge_tunnel": {"category":"line","geometry":"LineString","symbol":"512","nameSv":"Bro/tunnel","selectable":true,"publishable":true},
    "registration_mark": {"category":"point","geometry":"Point","symbol":"602","nameSv":"Passmärke","selectable":true,"publishable":true},
    "spot_height": {"category":"point","geometry":"Point","symbol":"603","nameSv":"Höjdangivelse","selectable":true,"publishable":true},
    "waterhole": {"category":"point","geometry":"Point","symbol":"303","nameSv":"Vattenhål","selectable":true,"publishable":true},
    "spring": {"category":"point","geometry":"Point","symbol":"312","nameSv":"Källa","selectable":true,"publishable":true},
    "prominent_water_feature": {"category":"point","geometry":"Point","symbol":"313","nameSv":"Tydligt vattenföremål","selectable":true,"publishable":true},
    "shallow_water": {"category":"area","geometry":"Polygon","symbol":"302","nameSv":"Grund vattenyta","selectable":true,"publishable":true},
    "impassable_marsh": {"category":"area","geometry":"Polygon","symbol":"307","nameSv":"Opasserbar sankmark","selectable":true,"publishable":true},
    "crossable_watercourse": {"category":"line","geometry":"LineString","symbol":"304","nameSv":"Passerbart vattendrag","selectable":true,"publishable":true},
    "narrow_marsh": {"category":"line","geometry":"LineString","symbol":"309","nameSv":"Smal sankmark","selectable":true,"publishable":true},
    "rough_open_land": {"category":"area","geometry":"Polygon","symbol":"403","nameSv":"Öppen mark med normal löpbarhet","selectable":true,"publishable":true},
    "cultivated_land": {"category":"area","geometry":"Polygon","symbol":"412","nameSv":"Odlad mark","selectable":true,"publishable":true},
    "paved_area": {"category":"area","geometry":"Polygon","symbol":"501","nameSv":"Belagd yta","selectable":true,"publishable":true},
    "course_start": {"category":"point","geometry":"Point","symbol":"701","nameSv":"Start","selectable":true,"publishable":true},
    "map_issue_point": {"category":"point","geometry":"Point","symbol":"702","nameSv":"Kartutdelningsplats","selectable":true,"publishable":true},
    "course_control": {"category":"point","geometry":"Point","symbol":"703","nameSv":"Kontroll","selectable":true,"publishable":true},
    "course_number": {"category":"point","geometry":"Point","symbol":"704","nameSv":"Kontrollsiffra","selectable":true,"publishable":true},
    "course_line": {"category":"line","geometry":"LineString","symbol":"705","nameSv":"Sammanbindningslinje","selectable":true,"publishable":true},
    "course_finish": {"category":"point","geometry":"Point","symbol":"706","nameSv":"Mål","selectable":true,"publishable":true},
    "marked_route": {"category":"line","geometry":"LineString","symbol":"707","nameSv":"Snitslad del","selectable":true,"publishable":true},
    "out_of_bounds_boundary": {"category":"line","geometry":"LineString","symbol":"708","nameSv":"Gräns förbjuden att passera","selectable":true,"publishable":true},
    "out_of_bounds_area": {"category":"area","geometry":"Polygon","symbol":"709","nameSv":"Förbjudet område (banpåtryck)","selectable":true,"publishable":true},
    "course_crossing": {"category":"point","geometry":"Point","symbol":"710","nameSv":"Passeringspunkt (banpåtryck)","selectable":true,"publishable":true},
    "forbidden_route": {"category":"line","geometry":"LineString","symbol":"711","nameSv":"Förbjuden väg","selectable":true,"publishable":true},
    "first_aid": {"category":"point","geometry":"Point","symbol":"712","nameSv":"Första hjälpen-plats","selectable":true,"publishable":true},
    "refreshment": {"category":"point","geometry":"Point","symbol":"713","nameSv":"Vätskeplats","selectable":true,"publishable":true},
    "map_exchange_start": {"category":"point","geometry":"Point","symbol":"715","nameSv":"Startpunkt efter kartbyte","selectable":true,"publishable":true},
    "boulder": {"category":"point","geometry":"Point","symbol":"204","nameSv":"Sten","selectable":true,"publishable":true},
    "boulder_large": {"category":"point","geometry":"Point","symbol":"205","nameSv":"Stor sten","selectable":true,"publishable":true},
    "knoll": {"category":"point","geometry":"Point","symbol":"109","nameSv":"Liten kulle","selectable":true,"publishable":true},
    "elongated_knoll": {"category":"point","geometry":"Point","symbol":"110","nameSv":"Liten långsträckt kulle","selectable":true,"publishable":true},
    "small_depression": {"category":"point","geometry":"Point","symbol":"111","nameSv":"Liten sänka","selectable":true,"publishable":true},
    "pit": {"category":"point","geometry":"Point","symbol":"112","nameSv":"Grop","selectable":true,"publishable":true},
    "rocky_pit_cave": {"category":"point","geometry":"Point","symbol":"203.1","nameSv":"Stengrop eller grotta","selectable":true,"publishable":true},
    "dangerous_pit": {"category":"point","geometry":"Point","symbol":"203.2","nameSv":"Farlig grop","selectable":true,"publishable":true},
    "gigantic_boulder": {"category":"area","geometry":"Polygon","symbol":"206","nameSv":"Jättesten eller klippelare","selectable":true,"publishable":true},
    "boulder_cluster": {"category":"point","geometry":"Point","symbol":"207","nameSv":"Stenkluster","selectable":true,"publishable":true},
    "tower": {"category":"point","geometry":"Point","symbol":"524","nameSv":"Högt torn","selectable":true,"publishable":true},
    "small_tower": {"category":"point","geometry":"Point","symbol":"525","nameSv":"Litet torn","selectable":true,"publishable":true},
    "cairn": {"category":"point","geometry":"Point","symbol":"526","nameSv":"Röse eller minnessten","selectable":true,"publishable":true},
    "fodder_rack": {"category":"point","geometry":"Point","symbol":"527","nameSv":"Foderhäck","selectable":true,"publishable":true},
    "prominent_manmade_ring": {"category":"point","geometry":"Point","symbol":"530","nameSv":"Framträdande människoskapat objekt – ring","selectable":true,"publishable":true},
    "prominent_manmade_x": {"category":"point","geometry":"Point","symbol":"531","nameSv":"Framträdande människoskapat objekt – kryss","selectable":true,"publishable":true},
    "prominent_large_tree": {"category":"point","geometry":"Point","symbol":"417","nameSv":"Framträdande stort träd","selectable":true,"publishable":true},
    "prominent_bush_tree": {"category":"point","geometry":"Point","symbol":"418","nameSv":"Framträdande buske eller träd","selectable":true,"publishable":true},
    "prominent_vegetation_feature": {"category":"point","geometry":"Point","symbol":"419","nameSv":"Framträdande vegetationsobjekt","selectable":true,"publishable":true},
    "well": {"category":"point","geometry":"Point","symbol":"311","nameSv":"Brunn, fontän eller vattentank","selectable":true,"publishable":true},
    "crossing_point": {"category":"point","geometry":"Point","symbol":"519","nameSv":"Passage genom barriär","selectable":true,"publishable":true},
    "rootstock": {"category":"point","geometry":"Point","symbol":null,"nameSv":"Rotvälta – ej normkopplad","selectable":false,"publishable":false},
    "paved_road": {"category":"line","geometry":"LineString","symbol":"502","nameSv":"Bred väg","selectable":true,"publishable":true},
    "road": {"category":"line","geometry":"LineString","symbol":"503","nameSv":"Väg","selectable":true,"publishable":true},
    "gravel_road": {"category":"line","geometry":"LineString","symbol":"504","nameSv":"Fordonsspår","selectable":true,"publishable":true},
    "wide_path": {"category":"line","geometry":"LineString","symbol":"505","nameSv":"Stig","selectable":true,"publishable":true},
    "path": {"category":"line","geometry":"LineString","symbol":"506","nameSv":"Liten stig","selectable":true,"publishable":true},
    "faint_path": {"category":"line","geometry":"LineString","symbol":"507","nameSv":"Otydlig liten stig","selectable":true,"publishable":true},
    "dry_ditch": {"category":"line","geometry":"LineString","symbol":"108","nameSv":"Litet torrt erosionsdike","selectable":true,"publishable":true},
    "minor_watercourse": {"category":"line","geometry":"LineString","symbol":"306","nameSv":"Mindre eller periodiskt vattenflöde","selectable":true,"publishable":true},
    "stream": {"category":"line","geometry":"LineString","symbol":"305","nameSv":"Mindre passerbart vattendrag","selectable":true,"publishable":true},
    "ditch": {"category":"line","geometry":"LineString","symbol":null,"nameSv":"Dike – behöver klassificeras","selectable":false,"publishable":false},
    "fence": {"category":"line","geometry":"LineString","symbol":"516","nameSv":"Staket","selectable":true,"publishable":true},
    "ruined_fence": {"category":"line","geometry":"LineString","symbol":"517","nameSv":"Raserat staket","selectable":true,"publishable":true},
    "impassable_fence": {"category":"line","geometry":"LineString","symbol":"518","nameSv":"Opasserbart staket","selectable":true,"publishable":true},
    "railway": {"category":"line","geometry":"LineString","symbol":"509","nameSv":"Järnväg","selectable":true,"publishable":true},
    "power_line": {"category":"line","geometry":"LineString","symbol":"510","nameSv":"Kraftledning","selectable":true,"publishable":true},
    "major_power_line": {"category":"line","geometry":"LineString","symbol":"511","nameSv":"Större kraftledning","selectable":true,"publishable":true},
    "wall": {"category":"line","geometry":"LineString","symbol":"513.1","nameSv":"Mur","selectable":true,"publishable":true},
    "retaining_wall": {"category":"line","geometry":"LineString","symbol":"513.2","nameSv":"Stödmur","selectable":true,"publishable":true},
    "ruined_wall": {"category":"line","geometry":"LineString","symbol":"514","nameSv":"Raserad mur","selectable":true,"publishable":true},
    "impassable_wall": {"category":"line","geometry":"LineString","symbol":"515","nameSv":"Opasserbar mur","selectable":true,"publishable":true},
    "prominent_line_feature": {"category":"line","geometry":"LineString","symbol":"528","nameSv":"Framträdande linjeobjekt","selectable":true,"publishable":true},
    "prominent_uncrossable_line_feature": {"category":"line","geometry":"LineString","symbol":"529","nameSv":"Framträdande opasserbart linjeobjekt","selectable":true,"publishable":true},
    "cultivation_boundary": {"category":"line","geometry":"LineString","symbol":"415","nameSv":"Tydlig odlingsgräns","selectable":true,"publishable":true},
    "stairway": {"category":"line","geometry":"LineString","symbol":"532","nameSv":"Trappa","selectable":true,"publishable":true},
    "cliff": {"category":"line","geometry":"LineString","symbol":"201","nameSv":"Ej passerbar brant","selectable":true,"publishable":true},
    "passable_cliff": {"category":"line","geometry":"LineString","symbol":"202","nameSv":"Brant","selectable":true,"publishable":true},
    "building": {"category":"area","geometry":"Polygon","symbol":"521","nameSv":"Byggnad","selectable":true,"publishable":true},
    "canopy": {"category":"area","geometry":"Polygon","symbol":"522","nameSv":"Skärmtak","selectable":true,"publishable":true},
    "ruin": {"category":"area","geometry":"Polygon","symbol":"523","nameSv":"Ruin","selectable":true,"publishable":true},
    "dense": {"category":"area","geometry":"Polygon","symbol":"408","nameSv":"Vegetation, gång","selectable":true,"publishable":true},
    "forest": {"category":"area","geometry":"Polygon","symbol":"405","nameSv":"Skog","selectable":true,"publishable":true},
    "slow_vegetation": {"category":"area","geometry":"Polygon","symbol":"406","nameSv":"Vegetation, långsam löpning","selectable":true,"publishable":true},
    "slow_vegetation_good_visibility": {"category":"area","geometry":"Polygon","symbol":"407","nameSv":"Vegetation, långsam löpning med god sikt","selectable":true,"publishable":true},
    "walk_vegetation_good_visibility": {"category":"area","geometry":"Polygon","symbol":"409","nameSv":"Vegetation, gång med god sikt","selectable":true,"publishable":true},
    "very_dense": {"category":"area","geometry":"Polygon","symbol":"410","nameSv":"Vegetation, mycket svår","selectable":true,"publishable":true},
    "open_land": {"category":"area","geometry":"Polygon","symbol":"401","nameSv":"Öppen mark","selectable":true,"publishable":true},
    "field": {"category":"area","geometry":"Polygon","symbol":"402","nameSv":"Öppen mark med spridda träd","selectable":true,"publishable":true},
    "clearcut": {"category":"area","geometry":"Polygon","symbol":"404","nameSv":"Ojämn öppen mark med spridda träd","selectable":true,"publishable":true},
    "marsh": {"category":"area","geometry":"Polygon","symbol":"308","nameSv":"Sankmark","selectable":true,"publishable":true},
    "indistinct_marsh": {"category":"area","geometry":"Polygon","symbol":"310","nameSv":"Otydlig sankmark","selectable":true,"publishable":true},
    "hard_marsh": {"category":"area","geometry":"Polygon","symbol":null,"nameSv":"Fast mark i myr – ej normkopplad","selectable":false,"publishable":false},
    "lake": {"category":"area","geometry":"Polygon","symbol":"301","nameSv":"Ej passerbar vattenyta","selectable":true,"publishable":true},
    "forbidden": {"category":"area","geometry":"Polygon","symbol":"520","nameSv":"Område som inte får beträdas","selectable":true,"publishable":true}
  },
  "aliases": {"stone":"boulder","large_boulder":"boulder_large","point_height":"knoll","dense_forest":"dense","very_dense_forest":"very_dense","open":"open_land"}
};
