window.OMAPMAKER_ISOM_REGISTRY = {
  "registryVersion": 1,
  "standard": "ISOM 2017-2 Revision 6",
  "symbols": {
    "101": {"nameSv":"Höjdkurva","nameEn":"Contour","geometry":["LineString"],"bindingRules":["5 m eller 2,5 m i genomgående flack terräng"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "102": {"nameSv":"Stödkurva","nameEn":"Index contour","geometry":["LineString"],"bindingRules":["Var femte höjdkurva"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "108": {"nameSv":"Litet erosionsdike","nameEn":"Small erosion gully","geometry":["LineString"],"bindingRules":["Torrt erosionsdike som är för smalt för symbol 107"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "109": {"nameSv":"Liten kulle","nameEn":"Small knoll","geometry":["Point"],"bindingRules":["Distinkt kulle som inte kan visas skalenligt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "112": {"nameSv":"Grop","nameEn":"Pit","geometry":["Point"],"bindingRules":["Distinkt grop som inte kan visas skalenligt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "201": {"nameSv":"Ej passerbar brant","nameEn":"Impassable cliff","geometry":["LineString"],"bindingRules":["Farlig eller omöjlig att passera"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "202": {"nameSv":"Brant","nameEn":"Cliff","geometry":["LineString"],"bindingRules":["Passerbar brant"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "204": {"nameSv":"Sten","nameEn":"Boulder","geometry":["Point"],"bindingRules":["Distinkt sten, normalt över 1 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "205": {"nameSv":"Stor sten","nameEn":"Large boulder","geometry":["Point"],"bindingRules":["Särskilt stor eller prominent sten, normalt över 2 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "301": {"nameSv":"Ej passerbar vattenyta","nameEn":"Uncrossable body of water","geometry":["Polygon","MultiPolygon"],"bindingRules":["Djupt eller farligt vatten"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "302": {"nameSv":"Grund vattenyta","nameEn":"Shallow body of water","geometry":["Polygon","MultiPolygon"],"bindingRules":["Mindre än 0,5 m djup och passerbar"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "303": {"nameSv":"Vattenhål","nameEn":"Waterhole","geometry":["Point"],"bindingRules":["Litet tydligt vattenobjekt"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "304": {"nameSv":"Passerbart vattendrag","nameEn":"Crossable watercourse","geometry":["LineString","MultiLineString"],"bindingRules":["Bredare än 2 m och passerbart"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "305": {"nameSv":"Mindre passerbart vattendrag","nameEn":"Small crossable watercourse","geometry":["LineString","MultiLineString"],"bindingRules":["Smalare än 2 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "306": {"nameSv":"Mindre eller periodiskt vattenflöde","nameEn":"Minor/seasonal water channel","geometry":["LineString","MultiLineString"],"bindingRules":["Litet, periodiskt eller otydligt vattenflöde"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "307": {"nameSv":"Ej passerbar sankmark","nameEn":"Uncrossable marsh","geometry":["Polygon","MultiPolygon"],"bindingRules":["Farlig eller ej passerbar sankmark"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "308": {"nameSv":"Sankmark","nameEn":"Marsh","geometry":["Polygon","MultiPolygon"],"bindingRules":["Passerbar sankmark"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "309": {"nameSv":"Smal sankmark","nameEn":"Narrow marsh","geometry":["LineString","MultiLineString"],"bindingRules":["Sankmark som är för smal för ytsymbol"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "310": {"nameSv":"Otydlig sankmark","nameEn":"Indistinct marsh","geometry":["Polygon","MultiPolygon"],"bindingRules":["Svag eller periodisk sankmark"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "311": {"nameSv":"Brunn, fontän eller vattentank","nameEn":"Well, fountain or water tank","geometry":["Point"],"bindingRules":["Distinkt vatteninstallation"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "312": {"nameSv":"Källa","nameEn":"Spring","geometry":["Point"],"bindingRules":["Distinkt källa"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "313": {"nameSv":"Särskilt vattenobjekt","nameEn":"Prominent water feature","geometry":["Point"],"bindingRules":["Betydelsen ska förklaras på kartan"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "401": {"nameSv":"Öppen mark","nameEn":"Open land","geometry":["Polygon","MultiPolygon"],"bindingRules":["Löpbar öppen mark"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "402": {"nameSv":"Öppen mark med spridda träd","nameEn":"Open land with scattered trees","geometry":["Polygon","MultiPolygon"],"bindingRules":["Löpbar öppen mark med spridda träd"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "403": {"nameSv":"Ojämn öppen mark","nameEn":"Rough open land","geometry":["Polygon","MultiPolygon"],"bindingRules":["Öppen mark med sämre löpbarhet"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "404": {"nameSv":"Ojämn öppen mark med spridda träd","nameEn":"Rough open land with scattered trees","geometry":["Polygon","MultiPolygon"],"bindingRules":["Klassificera efter löpbarhet och trädtäthet, inte markanvändningens namn"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "408": {"nameSv":"Vegetation, gång","nameEn":"Vegetation: walk","geometry":["Polygon","MultiPolygon"],"bindingRules":["Vegetation som normalt passeras gående"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "410": {"nameSv":"Vegetation, mycket svår","nameEn":"Vegetation: fight","geometry":["Polygon","MultiPolygon"],"bindingRules":["0–20 % av normal löphastighet"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "412": {"nameSv":"Odlad mark","nameEn":"Cultivated land","geometry":["Polygon","MultiPolygon"],"bindingRules":["Tillträdesförbud anges separat"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "501": {"nameSv":"Hårdgjord yta","nameEn":"Paved area","geometry":["Polygon","MultiPolygon"],"bindingRules":["Fast yta; minst 1 × 1 mm i tryck"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "502": {"nameSv":"Bred väg","nameEn":"Wide road","geometry":["LineString","MultiLineString"],"bindingRules":["Allvädersväg bredare än 5 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "503": {"nameSv":"Väg","nameEn":"Road","geometry":["LineString","MultiLineString"],"bindingRules":["Allvädersväg 3–5 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "504": {"nameSv":"Fordonsspår","nameEn":"Vehicle track","geometry":["LineString","MultiLineString"],"bindingRules":["Fordonsspår under 3 m; materialet avgör inte symbolen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "505": {"nameSv":"Stig","nameEn":"Footpath","geometry":["LineString","MultiLineString"],"bindingRules":["Tydlig stig"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "506": {"nameSv":"Liten stig","nameEn":"Small footpath","geometry":["LineString","MultiLineString"],"bindingRules":["Mindre men tydlig stig"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "507": {"nameSv":"Otydlig liten stig","nameEn":"Less distinct small footpath","geometry":["LineString","MultiLineString"],"bindingRules":["Svårföljd liten stig"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "509": {"nameSv":"Järnväg","nameEn":"Railway","geometry":["LineString","MultiLineString"],"bindingRules":["Förbjuden passage anges separat"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "510": {"nameSv":"Kraftledning, kabelbana eller skidlift","nameEn":"Power line, cableway or skilift","geometry":["LineString","MultiLineString","Point"],"bindingRules":["Stödmarkeringar ska motsvara exakta stolp- och mastlägen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "511": {"nameSv":"Större kraftledning","nameEn":"Major power line","geometry":["LineString","MultiLineString","Point"],"bindingRules":["Dubbel linje och exakta mastlägen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "513.1": {"nameSv":"Mur","nameEn":"Wall","geometry":["LineString","MultiLineString"],"bindingRules":["Betydande mur, normalt minst 1 m"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "516": {"nameSv":"Staket","nameEn":"Fence","geometry":["LineString","MultiLineString"],"bindingRules":["Betydande passerbart staket"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "520": {"nameSv":"Område som inte får beträdas","nameEn":"Area that shall not be entered","geometry":["Polygon","MultiPolygon"],"bindingRules":["Får inte beträdas; intern kartinformation ska begränsas enligt normen"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "521": {"nameSv":"Byggnad","nameEn":"Building","geometry":["Polygon","MultiPolygon"],"bindingRules":["Ritas skalenligt och generaliseras enligt minimimått"],"supportStatus":"partial","rendererStatus":"semantic-match"},
    "524": {"nameSv":"Högt torn","nameEn":"High tower","geometry":["Point"],"bindingRules":["Prominent högt torn eller mast"],"supportStatus":"partial","rendererStatus":"semantic-match"}
  },
  "manualTypes": {
    "boulder": {"category":"point","geometry":"Point","symbol":"204","nameSv":"Sten","selectable":true,"publishable":true},
    "boulder_large": {"category":"point","geometry":"Point","symbol":"205","nameSv":"Stor sten","selectable":true,"publishable":true},
    "knoll": {"category":"point","geometry":"Point","symbol":"109","nameSv":"Liten kulle","selectable":true,"publishable":true},
    "pit": {"category":"point","geometry":"Point","symbol":"112","nameSv":"Grop","selectable":true,"publishable":true},
    "tower": {"category":"point","geometry":"Point","symbol":"524","nameSv":"Högt torn","selectable":true,"publishable":true},
    "well": {"category":"point","geometry":"Point","symbol":"311","nameSv":"Brunn, fontän eller vattentank","selectable":true,"publishable":true},
    "rootstock": {"category":"point","geometry":"Point","symbol":null,"nameSv":"Rotvälta – ej normkopplad","selectable":false,"publishable":false},
    "paved_road": {"category":"line","geometry":"LineString","symbol":"502","nameSv":"Bred väg","selectable":true,"publishable":true},
    "road": {"category":"line","geometry":"LineString","symbol":"503","nameSv":"Väg","selectable":true,"publishable":true},
    "gravel_road": {"category":"line","geometry":"LineString","symbol":"504","nameSv":"Fordonsspår","selectable":true,"publishable":true},
    "wide_path": {"category":"line","geometry":"LineString","symbol":"505","nameSv":"Stig","selectable":true,"publishable":true},
    "path": {"category":"line","geometry":"LineString","symbol":"506","nameSv":"Liten stig","selectable":true,"publishable":true},
    "faint_path": {"category":"line","geometry":"LineString","symbol":"507","nameSv":"Otydlig liten stig","selectable":true,"publishable":true},
    "dry_ditch": {"category":"line","geometry":"LineString","symbol":"108","nameSv":"Litet torrt erosionsdike","selectable":true,"publishable":true},
    "minor_watercourse": {"category":"line","geometry":"LineString","symbol":"306","nameSv":"Mindre eller periodiskt vattenflöde","selectable":true,"publishable":true},
    "stream": {"category":"line","geometry":"LineString","symbol":"305","nameSv":"Mindre passerbart vattendrag","selectable":true,"publishable":true},
    "ditch": {"category":"line","geometry":"LineString","symbol":null,"nameSv":"Dike – behöver klassificeras","selectable":false,"publishable":false},
    "fence": {"category":"line","geometry":"LineString","symbol":"516","nameSv":"Staket","selectable":true,"publishable":true},
    "railway": {"category":"line","geometry":"LineString","symbol":"509","nameSv":"Järnväg","selectable":true,"publishable":true},
    "power_line": {"category":"line","geometry":"LineString","symbol":"510","nameSv":"Kraftledning","selectable":true,"publishable":true},
    "major_power_line": {"category":"line","geometry":"LineString","symbol":"511","nameSv":"Större kraftledning","selectable":true,"publishable":true},
    "wall": {"category":"line","geometry":"LineString","symbol":"513.1","nameSv":"Mur","selectable":true,"publishable":true},
    "cliff": {"category":"line","geometry":"LineString","symbol":"201","nameSv":"Ej passerbar brant","selectable":true,"publishable":true},
    "passable_cliff": {"category":"line","geometry":"LineString","symbol":"202","nameSv":"Brant","selectable":true,"publishable":true},
    "building": {"category":"area","geometry":"Polygon","symbol":"521","nameSv":"Byggnad","selectable":true,"publishable":true},
    "dense": {"category":"area","geometry":"Polygon","symbol":"408","nameSv":"Vegetation, gång","selectable":true,"publishable":true},
    "very_dense": {"category":"area","geometry":"Polygon","symbol":"410","nameSv":"Vegetation, mycket svår","selectable":true,"publishable":true},
    "open_land": {"category":"area","geometry":"Polygon","symbol":"401","nameSv":"Öppen mark","selectable":true,"publishable":true},
    "field": {"category":"area","geometry":"Polygon","symbol":"402","nameSv":"Öppen mark med spridda träd","selectable":true,"publishable":true},
    "clearcut": {"category":"area","geometry":"Polygon","symbol":"404","nameSv":"Ojämn öppen mark med spridda träd","selectable":true,"publishable":true},
    "marsh": {"category":"area","geometry":"Polygon","symbol":"308","nameSv":"Sankmark","selectable":true,"publishable":true},
    "indistinct_marsh": {"category":"area","geometry":"Polygon","symbol":"310","nameSv":"Otydlig sankmark","selectable":true,"publishable":true},
    "hard_marsh": {"category":"area","geometry":"Polygon","symbol":null,"nameSv":"Fast mark i myr – ej normkopplad","selectable":false,"publishable":false},
    "lake": {"category":"area","geometry":"Polygon","symbol":"301","nameSv":"Ej passerbar vattenyta","selectable":true,"publishable":true},
    "forbidden": {"category":"area","geometry":"Polygon","symbol":"520","nameSv":"Område som inte får beträdas","selectable":true,"publishable":true}
  },
  "aliases": {"stone":"boulder","large_boulder":"boulder_large","point_height":"knoll","dense_forest":"dense","very_dense_forest":"very_dense","open":"open_land"}
};
