const assert=require('node:assert/strict');
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
global.window=global;
for(const file of ['isom_symbols.js','isom_renderer.js'])vm.runInThisContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'));
const renderer=OMAPMAKER_ISOM_RENDERER, mx=111320*Math.cos(59*Math.PI/180);
const coordinate=(x,y)=>[18+x/mx,59+y/111320];
const metres=c=>[(c[0]-18)*mx,(c[1]-59)*111320];
const point=(id,x,y,symbol='204')=>({type:'Feature',id,properties:{symbol,source:'gps',accuracy:2},geometry:{type:'Point',coordinates:coordinate(x,y)}});
const line=(id,points,symbol='506',properties={})=>({type:'Feature',id,properties:{symbol,...properties},geometry:{type:'LineString',coordinates:points.map(p=>coordinate(...p))}});
const stone=point('stone',0,1),trail=line('trail',[[-100,0],[100,0]]),features=[stone,trail];
const before=JSON.stringify(features),placement=renderer.layoutBoulders(features).get(stone);
assert(placement.displaced);assert(!placement.unresolved);
// Stone radius 3m + path half-width 1.35m + 2.25m edge gap.
assert(Math.abs(metres(placement.coordinates)[1]-6.6)<.001);
assert.equal(JSON.stringify(features),before,'Never change surveyed coordinates or metadata');
for(const scale of [7500,10000,15000])assert.deepEqual(renderer.layoutBoulders(features,{scale}).get(stone),placement);
for(const zoom of [12,14,15,19,22])assert.deepEqual(renderer.layoutBoulders(features,{scale:15000,mode:'print',map:{getCenter:()=>({lat:59}),getZoom:()=>zoom}}).get(stone),placement);
const below=point('below',0,-1);assert(metres(renderer.layoutBoulders([below,trail]).get(below).coordinates)[1]<0,'Retain measured side');
const on=point('on',0,0);assert(renderer.layoutBoulders([on,trail]).get(on).displaced,'Exact coincidence has a deterministic escape');
const clear=point('clear',0,30);assert.deepEqual(renderer.layoutBoulders([clear,trail]).get(clear).coordinates,clear.geometry.coordinates);
assert(!renderer.layoutBoulders([stone,line('contour',[[-100,0],[100,0]],'101')]).get(stone).displaced,'Contours of another colour are exempt');
assert(!renderer.layoutBoulders([stone,{...trail,properties:{...trail.properties,status:'locally-excluded'}}]).get(stone).displaced);
const twin=point('twin',.2,1),pair=renderer.layoutBoulders([stone,twin,trail]);
const a=metres(pair.get(stone).coordinates),b=metres(pair.get(twin).coordinates);
assert(Math.hypot(a[0]-b[0],a[1]-b[1])>=8.25-1e-4,'Stone edges stay 0.15mm apart');
assert.deepEqual(renderer.layoutBoulders([trail,twin,stone]).get(stone),pair.get(stone),'Input ordering does not change placement');
const large=point('large',0,1,'205');assert(Math.abs(metres(renderer.layoutBoulders([large,trail]).get(large).coordinates)[1]-8.1)<.001);
const road=line('wide',[[-100,0],[100,0]],'502',{widthMetres:12});
assert(metres(renderer.layoutBoulders([stone,road]).get(stone).coordinates)[1]>=13.35-1e-4,'Include casing and actual road width');
const blocked=point('blocked',0,1),corridor=[line('lower',[[-100,0],[100,0]]),line('upper',[[-100,2],[100,2]])];
const unresolved=renderer.layoutBoulders([blocked,...corridor]).get(blocked);
assert(unresolved.unresolved);assert.deepEqual(unresolved.coordinates,blocked.geometry.coordinates,'Do not cross a path to escape a narrow gap');
const pit=point('pit',0,1,'112'),brownContour=line('brown-contour',[[-100,0],[100,0]],'101');
assert(renderer.layoutPointSymbols([pit,brownContour]).get(pit).displaced,'Ordinary brown point symbols keep their gap from brown contours');
const waterhole=point('waterhole',0,1,'303');
assert(!renderer.layoutPointSymbols([waterhole,brownContour]).get(waterhole).displaced,'The different-colour contour exception applies to ordinary point symbols');
const crossing=point('crossing',0,0,'519'),control=point('control',0,0,'703');
assert(!renderer.layoutPointSymbols([crossing,trail]).has(crossing),'Line-bound crossing symbols stay anchored to their barrier');
assert(!renderer.layoutPointSymbols([control,trail]).has(control),'Course symbols are outside cartographic spacing');
const powerLine=line('power',[[-100,0],[100,0]],'511',{supports:[{coordinates:coordinate(0,0),largeMast:false}]});
assert(metres(renderer.layoutPointSymbols([stone,powerLine]).get(stone).coordinates)[1]>13.9,'Ordinary points also clear the support mark, not only the power line');
const options={scale:15000,center:{lat:59,lng:18},declination:7,widthMm:100,heightMm:100};
assert(renderer.preflight([blocked,...corridor],options).issues.some(issue=>issue.code==='point-spacing-unresolved'));
const display=renderer.boulderPresentationFeatures(features,options);
assert.notDeepEqual(display[0].geometry.coordinates,stone.geometry.coordinates);
const svg=renderer.buildVectorSvg(features,options),expected=renderer.buildVectorSvg(display,options);
assert.equal(svg,expected,'Vector output uses the same layout and does not displace twice');
assert.equal(JSON.stringify(features),before,'Export must also preserve source data');
console.log('Point-symbol layout: edge gaps, side preservation, scale/zoom, clusters, casing, exclusions, contour rules, anchored symbols, bounded fallback and vector export passed.');
